---
- name: Reload prometheus
  ansible.builtin.command:
    argv: [docker, kill, --signal=HUP, prometheus]
  failed_when: false
  changed_when: true

- name: Reload alertmanager
  ansible.builtin.command:
    argv: [docker, kill, --signal=HUP, alertmanager]
  failed_when: false
  changed_when: true
