#!/usr/bin/env python3
"""Render ansible/inventories/production/hosts.yml from `terraform output -json`.

Terraform already writes the inventory on `apply`; CI uses this script so the
Ansible job can rebuild the same file from remote state without applying.

    terraform -chdir=terraform output -json > out.json
    python3 scripts/render-inventory.py --terraform-output out.json \
        --output ansible/inventories/production/hosts.yml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def load_inventory(terraform_output: dict[str, Any]) -> dict[str, Any]:
    block = terraform_output.get("ansible_inventory")
    if not isinstance(block, dict) or "value" not in block:
        raise SystemExit("terraform output does not contain 'ansible_inventory'")
    inventory = block["value"]
    nodes = inventory.get("nodes")
    if not isinstance(nodes, list) or not nodes:
        raise SystemExit("ansible_inventory.nodes is empty")
    return inventory


def render(inventory: dict[str, Any]) -> str:
    nodes = inventory["nodes"]
    lbs = inventory.get("load_balancers", {})
    first = nodes[0]["name"]
    lines = [
        "---",
        "# GENERATED BY scripts/render-inventory.py from Terraform output. Do not edit.",
        "all:",
        "  vars:",
        "    ansible_user: root",
        f"    qdrant_cluster_name: {inventory['cluster_name']}",
        f"    qdrant_environment: {inventory['environment']}",
        f"    qdrant_node_count: {len(nodes)}",
        f"    qdrant_bootstrap_private_ip: {inventory['bootstrap_private_ip']}",
        f"    qdrant_private_network_cidr: {lbs.get('network_ip_range', '')}",
        f"    qdrant_http_lb_public_ip: \"{lbs.get('http_public_ip', '')}\"",
        f"    qdrant_grpc_lb_public_ip: \"{lbs.get('grpc_public_ip', '')}\"",
        f"    qdrant_monitoring_lb_public_ip: \"{lbs.get('monitoring_public_ip', '')}\"",
        "  children:",
        "    qdrant:",
        "      hosts:",
    ]
    for node in nodes:
        lines += [
            f"        {node['name']}:",
            f"          ansible_host: {node['public_ip']}",
            f"          qdrant_node_id: {node['node_id']}",
            f"          qdrant_private_ip: {node['private_ip']}",
            f"          qdrant_data_dir: {node['data_dir']}",
        ]
    for group in ("qdrant_bootstrap", "qdrant_monitoring", "qdrant_backup_coordinator"):
        lines += [f"    {group}:", "      hosts:", f"        {first}: {{}}"]
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--terraform-output", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    payload = json.loads(args.terraform_output.read_text(encoding="utf-8"))
    inventory = load_inventory(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(inventory), encoding="utf-8")
    print(f"wrote {args.output} with {len(inventory['nodes'])} nodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
