---
# GENERATED BY TERRAFORM. Do not edit by hand; run `make inventory` instead.
all:
  vars:
    ansible_user: root
    qdrant_cluster_name: ${cluster_name}
    qdrant_environment: ${environment}
    qdrant_node_count: ${length(nodes)}
    qdrant_bootstrap_private_ip: ${bootstrap_private_ip}
    qdrant_private_network_cidr: ${load_balancers.network_ip_range}
    qdrant_http_lb_public_ip: "${load_balancers.http_public_ip}"
    qdrant_grpc_lb_public_ip: "${load_balancers.grpc_public_ip}"
    qdrant_monitoring_lb_public_ip: "${load_balancers.monitoring_public_ip}"
  children:
    qdrant:
      hosts:
%{ for node in nodes ~}
        ${node.name}:
          ansible_host: ${node.public_ip}
          qdrant_node_id: ${node.node_id}
          qdrant_private_ip: ${node.private_ip}
          qdrant_data_dir: ${node.data_dir}
%{ endfor ~}
    qdrant_bootstrap:
      hosts:
        ${nodes[0].name}: {}
    qdrant_monitoring:
      hosts:
        ${nodes[0].name}: {}
    qdrant_backup_coordinator:
      hosts:
        ${nodes[0].name}: {}
